# Generated by Django 5.1.7 on 2025-03-21 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Hotel Images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'webp', 'apng', 'avif', 'jpeg'])], verbose_name='Umrah Image')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
