# Generated by Django 5.1.7 on 2025-03-21 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('date', models.DateField(verbose_name='Date')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
